Dev
notKamui/Keval pull request #33
Opened 2023-02-10 20:57 UTC by Holo314

Solved the problem of expressions inside function parameters not count well by counting parentheses and automatically wrapping parameters of a function with extra layer of parentheses (e.g. `if(1*1,4,5)` -> `if((1*1),(4),(5))`  and `if((1*1),4,5)` -> `if(((1*1)),(4),(5))`)

2023-02-10 21:01 UTC, Holo314 commented
Should resolve #32

2023-02-11 13:02 UTC, notKamui requested changes
Everything seems good to me ; just a few changes for documentation sake and it's good to go

Thanks a lot for your contribution to this project (again !)

2023-02-11 14:46 UTC, notKamui commented on README.md
> +
good catch

2023-02-11 14:47 UTC, notKamui approved these changes
Thank you ! Closing this PR

2023-02-11 14:48 UTC, merged